Repository meateam/download-service, pull requests merged in 2019-06, with the labels that each got.

#27 Feature/refactor
  download/download.go
  download/download_test.go
  go.mod
  go.sum
  main.go
  proto/download_service.pb.go
  server/server.go
Labels: enhancement, refactor

#28 Develop - refactor
  download/download.go
  download/download_test.go
  go.mod
  go.sum
  main.go
  proto/download_service.pb.go
  server/server.go
Labels: bug, enhancement

#29 fix ignore urls separation by commas for the logger configuration
  .vscode/launch.json
  download/download.go
  download/download_test.go
  main.go
  server/server.go
Labels: bug

#30 Develop - fix ignore urls separation by commas for logger configuration
  .vscode/launch.json
  download/download.go
  download/download_test.go
  main.go
  server/server.go
Labels: bug

#32 update grpc_health_probe version and cleaned go.sum
  Dockerfile
  go.sum
Labels: enhancement, good first issue

#33 Hotfix/region
  download/download_test.go
  main.go
  server/server.go
Labels: bug, enhancement
